const INGREDIENT_EMOJIS: Record<string, string> = {
  yumurta: "🥚",
  peynir: "🧀",
  domates: "🍅",
  süt: "🥛",
  un: "🌾",
  et: "🥩",
  tavuk: "🍗",
  balık: "🐟",
  soğan: "🧅",
  sarımsak: "🧄",
  patates: "🥔",
  havuç: "🥕",
  biber: "🫑",
  mantar: "🍄",
  elma: "🍎",
  muz: "🍌",
  çilek: "🍓",
  portakal: "🍊",
  limon: "🍋",
  ekmek: "🍞",
  pirinç: "🍚",
  makarna: "🍝",
  zeytin: "🫒",
  bal: "🍯",
  tereyağı: "🧈",
  yoğurt: "🥣",
  salatalık: "🥒",
  marul: "🥬",
  ıspanak: "🥬",
  brokoli: "🥦",
  mısır: "🌽",
  fasulye: "🫘",
  nohut: "🫘",
  mercimek: "🫘",
  ceviz: "🌰",
  fındık: "🌰",
  badem: "🌰",
  çikolata: "🍫",
  şeker: "🍬",
  tuz: "🧂",
  baharat: "🌶️",
  zeytinyağı: "🫒",
  yağ: "🫒",
  su: "💧",
  kahve: "☕",
  çay: "🍵",
  sosis: "🌭",
  jambon: "🥓",
  patlıcan: "🍆",
  kabak: "🎃",
  avokado: "🥑",
  nar: "🍎",
  üzüm: "🍇",
  karpuz: "🍉",
  kavun: "🍈",
  krema: "🥛",
  maydanoz: "🌿",
  dereotu: "🌿",
  nane: "🌿",
  fesleğen: "🌿",
  kekik: "🌿",
  köfte: "🍖",
  sucuk: "🌭",
  pastırma: "🥓",
  lahana: "🥬",
  kıyma: "🥩",
  tavukgöğsü: "🍗",
  hindi: "🦃",
  karides: "🦐",
  midye: "🦪",
  somon: "🐟",
  ton: "🐟",
  kinoa: "🌾",
  yulaf: "🌾",
  bulgur: "🌾",
  şeftali: "🍑",
  armut: "🍐",
  kiraz: "🍒",
  vişne: "🍒",
  incir: "🫐",
  hurma: "🫐",
  kuruüzüm: "🍇",
  kuruincir: "🫐",
  tarçın: "🌿",
  vanilya: "🌿",
  kakao: "🍫",
  puding: "🍮",
  dondurma: "🍦",
  kremapeynir: "🧀",
  kaşar: "🧀",
  lor: "🧀",
  beyazpeynir: "🧀",
  mozarella: "🧀",
  parmesan: "🧀",
  sütlaç: "🍮",
  börek: "🥐",
  poğaça: "🥐",
  simit: "🥯",
  kurabiye: "🍪",
  kek: "🎂",
  pasta: "🎂",
  turşu: "🥒",
  salça: "🍅",
  ketçap: "🍅",
  mayonez: "🥚",
  hardal: "🌭",
  sirke: "🫗",
  limonsuyu: "🍋",
  portakalsuyu: "🍊",
  soda: "🥤",
  meyvesuyu: "🧃",
  bira: "🍺",
  şarap: "🍷",
  rakı: "🥃",
  viski: "🥃",
  votka: "🥃",
};

export function getIngredientEmoji(ingredient: string): string {
  const normalized = ingredient.toLowerCase().trim();

  for (const [key, emoji] of Object.entries(INGREDIENT_EMOJIS)) {
    if (normalized.includes(key)) {
      return emoji;
    }
  }

  return "🥘";
}

export const MEAL_TYPES = [
  { id: "Kahvaltı", label: "Kahvaltı", emoji: "🌅" },
  { id: "Ana Yemek", label: "Ana Yemek", emoji: "🍽️" },
  { id: "Ara Öğün", label: "Ara Öğün", emoji: "🥪" },
  { id: "Tatlı", label: "Tatlı", emoji: "🍰" },
  { id: "İçecek", label: "İçecek", emoji: "🥤" },
  { id: "Fırın Yemeği", label: "Fırın Yemeği", emoji: "🔥" },
  { id: "Çorba", label: "Çorba", emoji: "🍲" },
  { id: "Salata", label: "Salata", emoji: "🥗" },
  { id: "Fast Food", label: "Fast Food", emoji: "🍔" },
  { id: "Atıştırmalık", label: "Atıştırmalık", emoji: "🍿" },
  { id: "Diyet", label: "Diyet", emoji: "🥗" },
  { id: "Fark Etmez", label: "Fark Etmez", emoji: "✨" },
] as const;

export const MAX_TIMES = [
  { id: "10 dakika", label: "10 dakika", emoji: "⚡" },
  { id: "20 dakika", label: "20 dakika", emoji: "⏱️" },
  { id: "30 dakika", label: "30 dakika", emoji: "🕐" },
  { id: "45 dakika", label: "45 dakika", emoji: "🕑" },
  { id: "60 dakika", label: "60 dakika", emoji: "🕒" },
  { id: "Fark Etmez", label: "Fark Etmez", emoji: "✨" },
] as const;

export const SERVINGS_OPTIONS = [
  { id: "1", label: "1", emoji: "👤" },
  { id: "2", label: "2", emoji: "👥" },
  { id: "3", label: "3", emoji: "👨‍👩‍👦" },
  { id: "4", label: "4", emoji: "👨‍👩‍👧‍👦" },
  { id: "5+", label: "5+", emoji: "🎉" },
] as const;

export const DIFFICULTY_OPTIONS = [
  { id: "Kolay", label: "Kolay", emoji: "😊" },
  { id: "Orta", label: "Orta", emoji: "🤔" },
  { id: "Zor", label: "Zor", emoji: "🔥" },
  { id: "Fark Etmez", label: "Fark Etmez", emoji: "✨" },
] as const;
